# Generated by Django 5.1.1 on 2025-06-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_cat_unique_name_owner'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cat',
            name='unique_name_owner',
        ),
    ]
